sudo: required
git:
  # depth: 50
  submodules: false
services:
  - docker

before_install:
  - git clone https://github.com/technologiestiftung/bezirksregionenprofile.git ./client
script:
  - ls
  - echo "script"

after_success:
  - docker build -t technologiestiftung/bezirksregionenprofile-client ./client
  - docker build -t technologiestiftung/bezirksregionenprofile-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push technologiestiftung/bezirksregionenprofile-client
  - docker push technologiestiftung/bezirksregionenprofile-nginx